services:
  db:
    image: postgres:16-alpine
    container_name: flowers-store-db
    environment:
      POSTGRES_USER: flowers
      POSTGRES_PASSWORD: flowers
      POSTGRES_DB: flowers
    ports:
      - "5432:5432"
    volumes:
      - flowers_pgdata:/var/lib/postgresql/data

volumes:
  flowers_pgdata:
